name: CI Kubernetes Security & Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  detect-secrets:
    name: Detect Secrets with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yokawasa/action-setup-kube-tools@v0.11.2
        with:
          kubeconform: '0.5.0'
      - run: |
          kubeconform -summary -ignore-missing-schemas -ignore-filename-pattern '.github/*' -output json .

